name: Get Proxy Names
on:
  push:
    branches:
      - master
    paths:
      - 'blocks/proxy/asn/raw.txt'

jobs:
  built_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: '8.2'
      
      - name: Get Proxy Names
        run: |
          cd blocks/proxy/asn/
          php proxyNames.php

      - name: Push proxy.csv
        uses: X4BNet/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'blocks/proxy/asn/proxy.csv'
          destination_repo: '${{ github.repository }}'
          destination_folder: '/blocks/proxy/asn/'
          user_email: 'automation@munroenet.com'
          user_name: 'Automation Manager'
          destination_branch: "master"
